### ISSUE TITLE
Unable to add datasource

### ISSUE THREAD

**Issue by kkalmbach-rh** [influxdata/grafana-flightsql-datasource#104]
I just installed version 0.1.5 of the plugin into my grafana (version 8.5.0).

Then I go in and try to add a datasource, the main page comes up fine, I enter a datasource name and the url, but when I select the "auth type" dropdown and select anything other than none, I immediately get this error:

`DetailsError: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

Are there minimum versions of grafana that need to be used with this plugin?

Thanks

**Comment by helenosheaa** [comment]
Hi,

Yes the minimum Grafana version required is 9.2.5 due to certain grafana packages we are using in the ui.

This is in our plugin.json but seems to have been missed out from the read me I'll make sure to update.

Please reopen this if you have any other issues!
