### ISSUE TITLE
Add view-type to the query builder

### ISSUE THREAD

**Issue by brettbuddin** [influxdata/grafana-flightsql-datasource#36]
I'm realizing now that it's much easier to deal with the long-to-wide conversion if we know the intension of the user in running the query. Instead of attempting to detect time-series rendering, I think we should make that a toggle-able thing in the UI. We've seen this in other plugins where there's a dropdown for rendering time-series or a table.

At that point we won't end up in a case of doing the table format conversion when we don't have to. If they have asked for a table of data, then we can keep it long format. Otherwise we'll make an effort to convert it to wide.

**Comment by helenosheaa** [comment]
add a timeseries/table type dropdown, determine what the default should be

**Comment by brettbuddin** [comment]
This will send a `format` field along with the query that is one of two values: `table` (default) or `time_series`. I was thinking that `time_series` should be the default, but I'm second guessing that now. If you request `time_series`, I verify that the resulting data has a `time` field in it, because otherwise the long-to-wide conversion wouldn't work. I'm leaning toward making `table` the default, because it's the least prescriptive about your intentions in the default state. However, it does mean that in order to do time series you'll have to add a `time` projection *and* flip this dropdown to "Time Series".

Thoughts?

**Comment by helenosheaa** [comment]
I think if we are currently setting the default to table that makes sense. However the fact that we had been doing some work with the time field to make timeseries work with little effort is a pretty big case for having that as the default.

If table is the default we can add to our help me docs what's needed to make timeseries work.
